### ISSUE TITLE
Subcontroller board from the Application Video

### ISSUE THREAD

**Issue by jgueldenstein** [NUbots/NUware#1]
Hey guys, any chance you could upload the design files for the subcontroller board from the application Video?

Jasper from the Hamburg Bit-Bots

**Comment by Bidski** [comment]
Hi Jasper,

We're currently still validating that all the electronics on the board are working correctly.

Once we are confident that they are all working as intended we will start releasing more information.

For future reference, such questions can be directed to our public gitter channel at https://gitter.im/NUbots/NUbots
